### ISSUE TITLE
data loss on delete-trailing-whitespace

### ISSUE THREAD

**Issue by svjatoslavagejenko** [zenozeng/yafolding.el#13]
Hi! AWESOME plugin!

But,
when I open relatively large text file in text mode and then
fold some parts of it. And then execute delete-trailing-whitespace
(I had it actually on before-save-hook)  then most of the folded text
disappears, leaving only one or 2 first lines of the folded text intact.

I use GNU Emacs 24.4.50.1 on Debian Wheezy 64bit.
Do you need more detailed configuration / example files to reproduce ?
 
Best regards,
Svjatoslav

**Comment by therockmandolinist** [comment]
Hey there, I saw this was re-opened. Has this been fixed? I haven't experienced any issues so far, but I wouldn't want to lose data... I'm also not sure where to put the fix on the front page.

**Comment by zenozeng** [comment]
@therockmandolinist Sorry for my late response. Sorry this issue won't be fixed. The data loss will happen if you call delete-trailing-whitespace when something in this file is folded. If you have to call delete-trailing-whitespace, wrap it with:

```
(lambda ()
    (yafolding-show-all)
    (delete-trailing-whitespace))
```

**Comment by therockmandolinist** [comment]
As a suggestion, it might be better to leave this as an open as a known issue and tag it with 'help wanted' or something like that. It would make the issue more visible to people to know about as well as anyone who might know how to fix it.
