### ISSUE TITLE
Cannot fold parent of multiple children

### ISSUE THREAD

**Issue by cataclysmic** [zenozeng/yafolding.el#23]
Hey zenozeng,

at first thanx for this plugin. It's the first that works for me.
I just have trouble folding parents of multiple children. It apparently only folds the first child for me.
E.g.
```
* parent comment
   * child 1 comment
        code
        code
        code
   * child 2 comment
        code
        code
        code
```

When trying to fold the parent I end with something like this:
```
* parent comment ...
    * child 2 comment ....
```
Apparently it does not recognize the 2nd child. Or did I make a mistake?

**Comment by cataclysmic** [comment]
I just found out it only happens if the children are folded.
It works if the children are unfolded.

**Comment by zenozeng** [comment]
![image](https://cloud.githubusercontent.com/assets/2544489/17076964/a61f9826-50f2-11e6-829d-b49a2ff70657.png)

Seems that line 3 becomes current-indentation: 0

**Comment by zenozeng** [comment]
```
current indentation: 0, should ingore current line: nil
```
