### ISSUE TITLE
can i set foldlevel like vim?

### ISSUE THREAD

**Issue by maple-leaf** [zenozeng/yafolding.el#24]
In vim , I can `:set foldlevel=3` to make code collapsed to take a outline view for specify level of code. can I do this with `yafolding`? thanks :)

**Comment by zenozeng** [comment]
@maple-leaf Sorry for my late response, you can use `(yafolding-toggle-all YOUR-INDENT-LEVEL)`.

![image](https://cloud.githubusercontent.com/assets/2544489/17077017/29dce0dc-50f4-11e6-9e06-537bda6c64cc.png)

![image](https://cloud.githubusercontent.com/assets/2544489/17077025/60cca35c-50f4-11e6-8b81-f56bc0b1dae9.png)

![image](https://cloud.githubusercontent.com/assets/2544489/17077019/2fc89e00-50f4-11e6-920b-be664f85fd4b.png)
